// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vysyx_220578_npc_onecycle.cpp"
#include "Vysyx_220578_npc_onecycle___024root.cpp"
#include "Vysyx_220578_npc_onecycle___024unit.cpp"
#include "Vysyx_220578_npc_onecycle__Dpi.cpp"
#include "Vysyx_220578_npc_onecycle__Trace.cpp"
#include "Vysyx_220578_npc_onecycle___024root__Slow.cpp"
#include "Vysyx_220578_npc_onecycle___024unit__Slow.cpp"
#include "Vysyx_220578_npc_onecycle__Syms.cpp"
#include "Vysyx_220578_npc_onecycle__Trace__Slow.cpp"
